var allResult = {
  mode: "all",
  tests: [
    // Problem 1 written
    {
      number: "1a",
      name: "NumPy tutor session link",
      description: "NumPy tutor session link",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1b",
      name: "Matrix multiplication complexity",
      description: "Matrix multiplication complexity",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1c",
      name: "Einsum tutor session link",
      description: "Einsum tutor session link",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1d",
      name: "Einstein summation (written)",
      description: "Einstein summation (written)",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },

    // Problem 1 code
    {
      number: "1e-0-basic",
      name: "linear_project small deterministic",
      description: "linear_project with bias (small deterministic)",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "1e-1-hidden",
      name: "linear_project randomized",
      description: "linear_project randomized, with bias",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1f-0-basic",
      name: "split_last_dim reshape check",
      description: "split_last_dim reshape check",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "1f-1-hidden",
      name: "split_last_dim randomized",
      description: "split_last_dim randomized shapes",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1g-0-basic",
      name: "normalized_inner_products small case",
      description: "normalized_inner_products small case + normalization",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "1g-1-hidden",
      name: "normalized_inner_products randomized",
      description: "normalized_inner_products randomized",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1h-0-basic",
      name: "mask_strictly_upper basic",
      description: "mask_strictly_upper sets upper triangle to -inf",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "1h-1-hidden",
      name: "mask_strictly_upper randomized",
      description: "mask_strictly_upper randomized",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "1i-0-basic",
      name: "prob_weighted_sum deterministic",
      description: "prob_weighted_sum small deterministic",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "1i-1-hidden",
      name: "prob_weighted_sum randomized",
      description: "prob_weighted_sum randomized normalized probs",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },

    // Problem 2 written
    {
      number: "2a",
      name: "Gradient warmup",
      description: "Gradient warmup",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "2c",
      name: "Matrix multiplication gradient",
      description: "Matrix multiplication gradient",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    // {
    //   number: "2e",
    //   name: "Vector gradient derivation",
    //   description: "Vector gradient derivation",
    //   max_seconds: null,
    //   max_points: 3,
    //   extra_credit: false,
    //   basic: false,
    // },

    // Problem 2 code
    {
      number: "2b-0-basic",
      name: "gradient_warmup deterministic",
      description: "gradient_warmup deterministic",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "2b-1-hidden",
      name: "gradient_warmup randomized",
      description: "gradient_warmup randomized",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "2d-0-basic",
      name: "matrix_grad deterministic",
      description: "matrix_grad deterministic",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "2d-1-hidden",
      name: "matrix_grad randomized",
      description: "matrix_grad randomized + numeric check",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "2e-0-basic",
      name: "finite differences single case",
      description: "finite differences matches analytic gradient (single case)",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "2e-1-hidden",
      name: "finite differences randomized",
      description:
        "finite differences matches analytic gradient (random cases)",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },

    // Problem 3 written
    {
      number: "3a",
      name: "Weighted scalar quadratic minimizer",
      description: "Weighted scalar quadratic minimizer",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "3b",
      name: "Gradient descent tutor session link",
      description: "Gradient descent tutor session link",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },

    // Problem 3 code
    {
      number: "3c-0-basic",
      name: "GD quadratic deterministic",
      description:
        "gradient descent converges to weighted average (deterministic)",
      max_seconds: 5,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: "3c-1-hidden",
      name: "GD quadratic randomized",
      description: "gradient descent converges on random instances",
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },

    // Problem 4 (Ethics in AI) written
    {
      number: "4a",
      name: "Ethics in AI part a",
      description: "Ethics in AI part a",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4b",
      name: "Ethics in AI part b",
      description: "Ethics in AI part b",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4c",
      name: "Ethics in AI part c",
      description: "Ethics in AI part c",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4d",
      name: "Ethics in AI part d",
      description: "Ethics in AI part d",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
  ],
  leaderboard: [],
};
